// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB319nGqz1pjAHaNNwHnDoLPVWvIox5mG0',
    appId: '1:41333039396:android:3f13d159c7fb50820153b1',
    messagingSenderId: '41333039396',
    projectId: 'one-vnu',
    storageBucket: 'one-vnu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJZk_Ory9ng9gAyhWozklHA7xN1KtgBtk',
    appId: '1:41333039396:ios:5030131881bf4c7a0153b1',
    messagingSenderId: '41333039396',
    projectId: 'one-vnu',
    storageBucket: 'one-vnu.appspot.com',
    iosBundleId: 'com.vnu.students',
  );

  //Project test push
  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDVhllttuwVyxR0bqCkud9Tq6ARSM0FXLE',
  //   appId: '1:41333039396:ios:13b60709cb9bc6460153b1',
  //   messagingSenderId: '41333039396',
  //   projectId: 'one-vnu',
  //   storageBucket: 'one-vnu.appspot.com',
  //   iosBundleId: 'com.kgroup.full',
  // );
}